version: "3.4"

services:
    php:
        build:
            context: .
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        restart: unless-stopped
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            SYMFONY_VERSION:

    caddy:
        build:
            context: .
            target: symfony_caddy
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
        restart: unless-stopped
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - caddy_data:/data
            - caddy_config:/config

    ###> symfony/mercure-bundle ###
    mercure:
      # In production, you may want to use the managed version of Mercure, https://mercure.rocks
      image: dunglas/mercure
      environment:
        # You should definitely change all these values in production
        - JWT_KEY=!ChangeMe!
        - ALLOW_ANONYMOUS=1
        - CORS_ALLOWED_ORIGINS=*
        - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337
        - DEMO=1
      ports:
        - "1337:80"
    ###< symfony/mercure-bundle ###

volumes:
    caddy_data:
    caddy_config:
