<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQiWPce\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQiWPce/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFQiWPce.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFQiWPce\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFQiWPce\App_KernelDevDebugContainer([
    'container.build_hash' => 'FQiWPce',
    'container.build_id' => '6f140f39',
    'container.build_time' => 1604520621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQiWPce');
