<?php

namespace ContainerFQiWPce;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TsUHGSNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TsUHGSN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TsUHGSN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'publisher' => ['privates', 'mercure.hub.default.publisher.traceable', 'getMercure_Hub_Default_Publisher_TraceableService', true],
        ], [
            'publisher' => '?',
        ]);
    }
}
